name: nlp_text_cleaner
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.8.13
  - setuptools=63.4.1
  - sqlite=3.39.3
  - wheel=0.37.1
  - pip:
    - astroid==2.12.12
    - attrs==22.1.0
    - autocorrect==2.6.1
    - black==22.10.0
    - build==0.8.0
    - colorama==0.4.6
    - coverage==6.5.0
    - exceptiongroup==1.0.0rc9
    - iniconfig==1.1.1
    - isort==5.10.1
    - joblib==1.2.0
    - langdetect==1.0.9
    - lazy-object-proxy==1.7.1
    - mccabe==0.7.0
    - mypy-extensions==0.4.3
    - nltk==3.7
    - packaging==21.3
    - pathspec==0.10.1
    - pep517==0.13.0
    - pip-tools==6.9.0
    - platformdirs==2.5.2
    - pylint==2.15.5
    - pyparsing==3.0.9
    - pytest==7.2.0
    - pytest-cov==4.0.0
    - regex==2022.9.13
    - six==1.16.0
    - tomli==2.0.1
    - tomlkit==0.11.5
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - wrapt==1.14.1
