name: nlp_text_cleaner
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.8.13
  - setuptools=63.4.1
  - sqlite=3.39.3
  - wheel=0.37.1
  - pip:
    - astroid==2.12.12
    - attrs==22.1.0
    - autocorrect==2.6.1
    - black==22.10.0
    - bleach==5.0.1
    - build==0.8.0
    - charset-normalizer==2.1.1
    - colorama==0.4.6
    - commonmark==0.9.1
    - coverage==6.5.0
    - docutils==0.19
    - exceptiongroup==1.0.0rc9
    - idna==3.4
    - importlib-metadata==5.0.0
    - iniconfig==1.1.1
    - isort==5.10.1
    - joblib==1.2.0
    - keyring==23.9.3
    - langdetect==1.0.9
    - lazy-object-proxy==1.7.1
    - mccabe==0.7.0
    - mypy-extensions==0.4.3
    - nltk==3.7
    - packaging==21.3
    - pathspec==0.10.1
    - pep517==0.13.0
    - pip-tools==6.9.0
    - pkginfo==1.8.3
    - platformdirs==2.5.2
    - pygments==2.13.0
    - pylint==2.15.5
    - pyparsing==3.0.9
    - pytest==7.2.0
    - pytest-cov==4.0.0
    - readme-renderer==37.2
    - regex==2022.9.13
    - requests==2.28.1
    - requests-toolbelt==0.10.1
    - rfc3986==2.0.0
    - rich==12.6.0
    - six==1.16.0
    - tomli==2.0.1
    - tomlkit==0.11.5
    - tqdm==4.64.1
    - twine==4.0.1
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - webencodings==0.5.1
    - wrapt==1.14.1
    - zipp==3.10.0
